### ISSUE TITLE
Implement versioning / tagging

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/janusgraph-docker#5]

**Comment by bobvanluijt** [comment]
Hi @moretea, not sure I understand the aim of this issue. Is this related to the version number set in the Swagger file? See [these docs](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/contribute/contributing.md#versioning).

**Comment by moretea** [comment]
No, separate versioning of the janusgraph-docker image.

**Comment by bobvanluijt** [comment]
Check

**Comment by idcrosby** [comment]
First option that comes to mind is to tag the repo (and docker image) with the version of janusgraph itself.

**Comment by moretea** [comment]
Yes, that sounds great :)
